name: devops-project

services:
  end-to-end-spring:
    container_name: backend
    image: ahmedevops/end-to-end-spring:latest
    ports:
      - "8085:8085"
    ## Tempo
  frontend:
    container_name: frontend
    build:
      context: ./frontend
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    depends_on:
      - end-to-end-spring
